# Use this to build and run the Micro-ROS client.

FROM ros:foxy-ros-base-focal

ENV DEBIAN_FRONTEND noninteractive

# Install basic tools.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        sudo \
        ccache \
        vim \
        nano \
        wget \
        apt-utils \
        gdb \
        less \
    && rm -rf /var/lib/apt/lists/*

# Setup links for ccache.
RUN cd /usr/local/bin/ \
    && ln -s ccache gcc && ln -s ccache g++ \
    && ln -s ccache cc && ln -s ccache c++

# Install ROS2 packages.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ros-foxy-desktop=0.9.2-1* \
        python3-vcstool \
    && rm -rf /var/lib/apt/lists/*

# Add MicroROS specific packages and an editor.
# The packages were identified when running create_agent.sh.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3-pip \
        libfl-dev libfl2 \
        bison \
        libncurses-dev libncurses5-dev \
        usb.ids usbutils \
        binfmt-support \
        clang-10 clang-tidy-10 clang-tools-10 \
        cpp-9 g++-9 gcc-10-base gcc-9 gcc-9-base lib32gcc-s1 \
        lib32stdc++6 libasan5 libatomic1 libc6-i386 libcc1-0 \
        libclang-common-10-dev libclang-cpp10 libgc1c2 \
        libgcc-9-dev libgcc-s1 libgfortran5 libgomp1 libitm1 \
        liblsan0 libobjc-9-dev libobjc4 libomp-10-dev libomp5-10 libpfm4 \
        libpipeline1 libquadmath0 libstdc++-9-dev libstdc++6 libtsan0 \
        libubsan1 libz3-4 libz3-dev llvm-10 llvm-10-dev llvm-10-runtime llvm-10-tools \
        clang-tidy \
        libasio-dev \
    && rm -rf /var/lib/apt/lists/*

# Create user with UID and GID matching those on my PC.
# This allows the user to delete build products created in the source tree.
# Also add user build to sudoers list.
RUN groupadd -g 1000 build && \
    useradd -u 1000 -g 1000 -m -s /bin/bash build && \
    mkdir -p /etc/sudoers.d/ && \
    echo "build ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/build && \
    chmod 0440 /etc/sudoers.d/build
ENV HOME /home/build

# Source ROS2 setup script for each shell.
RUN echo ". /opt/ros/foxy/setup.bash" > /home/build/.bash_aliases

# Change ownership of build directory to build:build.
RUN chown -R build:build /home/build/

# Use display
ENV DISPLAY :1.0

# Change to user build.
USER build
