# Copied from
# https://github.com/micro-ROS/micro_ros_espidf_component/blob/foxy/docker/Dockerfile
# Changed name of user to 'build' and install script.

FROM espressif/idf:release-v4.1

ENV DEBIAN_FRONTEND noninteractive
RUN echo "Set disable_coredump false" >> /etc/sudo.conf
RUN apt-get update -q && \
    apt-get install -y \
    sudo \
    lsb-release \
    gosu \
    nano && \
    rm -rf /var/lib/apt/lists/*

ARG TZ_ARG=UTC
ENV TZ=$TZ_ARG
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./install_micro_ros_deps_script.bash /install_micro_ros_deps_script.sh

RUN mkdir -p /tmp/install_micro_ros_deps_script && mv /install_micro_ros_deps_script.sh /tmp/install_micro_ros_deps_script/ && \
    /tmp/install_micro_ros_deps_script/install_micro_ros_deps_script.sh && \
    rm -rf /var/lib/apt/lists/*

ARG USER_ID=build

RUN useradd --create-home --home-dir /home/$USER_ID --shell /bin/bash --user-group --groups adm,sudo $USER_ID && \
    echo $USER_ID:$USER_ID | chpasswd && \
    echo "$USER_ID ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Add build user to the dialout group to be able to write the serial USB device.
RUN sed "s/^dialout.*/&$USER_ID/" /etc/group -i \
    && sed "s/^root.*/&$USER_ID/" /etc/group -i

# Source ESP IDF setup script for each shell.
RUN echo ". /opt/esp/idf/export.sh" > /home/$USER_ID/.bash_aliases

ARG USER_ID
USER $USER_ID
